### PR TITLE
added ecr subject_areas column to schema

### PR DESCRIPTION
**Pull request by de-code**
part of https://github.com/elifesciences/issues/issues/5177

see https://github.com/elifesciences/data-pipeline-ejp-config/pull/7#discussion_r340588054

### CODE REVIEW

**Review by tayowonibi — APPROVED** [review]

**Comment by de-code** [comment]
Hi @giorgiosironi would you be available to apply the schema change via builder / Terraform? (to `ci`, `staging`, `prod`)

Hopefully not a huge diff again and it should be able to just add the field.

**Comment by giorgiosironi** [comment]
Yes, is there a PR already?

**Comment by de-code** [comment]
> Yes, is there a PR already?

Yes, this one :-)

There is no change to the builder config as the schema was already linked. But the linked schema has now changed (and was merged).

**Comment by giorgiosironi** [comment]
Ok, steam rolling the changes to all environments.

**Comment by giorgiosironi** [comment]
`ci`: 7 changes, probably just orders.
`staging`: 8 changes, probably similar.
`prod`: 3 changes.

**Comment by de-code** [comment]
Happy to review what TerraForm is planning to do. Mostly concerned if it was planning to re-create tables in `prod`. Otherwise it should be okay (but can look in more detail).

**Comment by giorgiosironi** [comment]
No re-creations, only changes; they would fail if it were to actually make incompatible changes (rather than dropping). Applied everything and now still shows:
- `ci`: 7 changes
- `staging`: 8 changes.
- `prod`: 3 changes.
so we can be confident this is just fields being out of order.
I saved a [`prod` diff](https://gist.github.com/giorgiosironi/717f83e131e8b70bfe34a5d49354085e) if you want to look at it.

**Comment by de-code** [comment]
Okay, great. My new column is there and tables don't seem to be empty. So that you!

Is it worth looking into why it still shows a diff? Do you have similar issues with other projects?

**Comment by giorgiosironi** [comment]
We don't use BigQuery elsewhere off the top of my head, so this is an issue for the GCP Terraform provider; there may be something on their [bug tracker](https://github.com/terraform-providers/terraform-provider-google/issues) but can't find anything at the moment.

**Pull request merged**
